project_name = "Tendon"
bundle = "com.davidaflood.tendon"
version = "0.19"
url = "https://github.com/d-flood/Tendon"
license = "MIT license"
author = "David Flood"
author_email = "davidfloodii@gmail.com"

formal_name = "Tendon"
description = "a suite of tools for integrating transcription and collation software"
icon = "src/tendon/resources/tendon"
sources = ["src/tendon"]
requires = [
    "lxml",
    "natsort",
    "PySimpleGUI",
    "Markdown==3.2.2",
    "markdown-del-ins",
    "toml",
    "python-docx==0.8.11"
]
